### ISSUE TITLE
datetime formatting not working for some reason

### ISSUE THREAD

**Issue by evz** [datamade/clearstreets-processing#12]
Looks like the [`formatTime`](https://github.com/open-city/clearstreets-processing/blob/master/processors/slurper.py#L153-L154) method of the `Slurper` class is throwing errors:

```
Traceback (most recent call last):
  File "clear_streets.py", line 49, in <module>
    slurper.run(recreate=args.recreate_tables)
  File "/home/datamade/clearstreets-processing/processors/slurper.py", line 161, in run
    self.insertPoints(route_point)
  File "/home/datamade/clearstreets-processing/processors/slurper.py", line 113, in insertPoints
    point['posting_time'] = self.formatTime(point['posting_time'])
  File "/home/datamade/clearstreets-processing/processors/slurper.py", line 154, in formatTime
    return datetime.datetime(*time.strptime(s, self.time_format)[:6])
  File "/usr/local/lib/python3.4/_strptime.py", line 501, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/usr/local/lib/python3.4/_strptime.py", line 344, in _strptime
    (data_string, format))
ValueError: time data 'Mon Jan 04 09:41:12 CST 2016' does not match format '%a %b %d %H:%M:%S %Z %Y'
```

**Comment by fgregg** [comment]
weird.

Also don't know why it's not just

```
datetime.datetime.strptime(s, self.time_format)
```

**Comment by evz** [comment]
I was able to sidestep this by just using the python dateutil module (2f85fe0f605c14b249e3b9a24e30a6a3e78dbc8a). Seems to be working now.
